# Generated by Django 3.1.4 on 2020-12-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_outing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='rat',
            name='outfits',
            field=models.ManyToManyField(to='main_app.Outfit'),
        ),
    ]
