# Generated by Django 3.1.4 on 2021-01-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210104_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='rat',
        ),
        migrations.AddField(
            model_name='rat',
            name='outfits',
            field=models.ManyToManyField(to='main_app.Outfit'),
        ),
    ]
